# Generated by Django 6.0.3 on 2026-03-12 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carro_chamado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carros', models.CharField(max_length=100)),
                ('horario', models.DateTimeField(default=django.utils.timezone.now)),
                ('desfeita', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['horario'],
            },
        ),
    ]
