# Generated by Django 6.0.3 on 2026-03-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicochamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='entrou_na_fila_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
